# Generated by Django 4.1.1 on 2022-09-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario_alter_evento_data_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
